### ISSUE TITLE
Middleware for Web3.py

### ISSUE THREAD

**Issue by CoreytMayweather** [gochain-io/rpc-proxy#46]
When calling certain function & properties in web3.py, python developers aren’t allowed access. I talked to some of the web3.py developers and they say a middleware is needed. A middleware for POA has been created. Would anybody be able to assist in creating a middleware for GoChain in Web3.py?
![A510BEA2-084B-41CD-A74C-8C7E31B69544](https://user-images.githubusercontent.com/42082720/57228462-769b8200-6fd9-11e9-8aa5-590c8939b325.png)

**Comment by treeder** [comment]
@brockmcblockchain you know python, thoughts on this?

@CoreytMayweather what data are you trying to get specifically?

**Comment by jmank88** [comment]
Do we know the specific error that is occurring? The block headers are 99% the same, and the only differences would be on epoch blocks IIRC (which are very rare).

Is it possible that the code is calling blocked methods on the public proxy?

**Comment by jmank88** [comment]
It's also possible that the existing Rinkeby middleware could be used as-is.

**Comment by brockmcblockchain** [comment]
I'll put a few minutes into this and whip up a demo.  I used web3.py without issues but I don't know what functions we're trying to access.  Can we have an example to test against for an acceptance test?

**Comment by CoreytMayweather** [comment]
Trying to get node version via "w3.version.node",  syncing data using w3.eth.syncing and trying to assign default accounts using the w3.eth.defaultaccount methods. all give me this exact screen
![Screenshot (117)](https://user-images.githubusercontent.com/42082720/57260692-6069e200-702a-11e9-85d9-649a2aa28b47.png) 

Also this is at the bottom page of Middleware, maybe applies to Gochain also?
![Screenshot (119)](https://user-images.githubusercontent.com/42082720/57260759-a626aa80-702a-11e9-9888-663f34012552.png)

**Comment by treeder** [comment]
All of those methods only make sense when talking to a local node, are you trying to connect to a local node or to our RPC endpoints?

**Comment by CoreytMayweather** [comment]
Ok thanks @treeder
